describe('util/node', () => {
  test('get the direction of a point to the center of the bbox', () => {})
  test('get the bbox of node', () => {})
  test('get the points on expand bbox', () => {})
  test('get hull of bboxes', () => {})
  test('merge two bbox', () => {})
  test('if a segment cross the node', () => {})
  test('if two segments are intersected', () => {})
  test('get the intersection of two segments', () => {})
  test('get the intersection of a line segment and a rectangle', () => {})
  test('get the intersections of cross lien of point and bbox', () => {})
  test('if two bbox is overlapped', () => {})
  test('get closest anchor of a node and a position', () => {})
  test('if a point on the border of the rectangle', () => {})
  test('get the intersections of cross line of point and circle', () => {})
  test('get the height of the text in dom', () => {})
})
